#!/bin/bash

# Nginx version variables
if [[ -z $NGINX_VERSION ]]; then
	NGINX_VERSION="1.18.0-2"
fi
if [[ -z $NGINX_CODENAME ]]; then
	NGINX_DIST="buster"
fi

# New codename for built package
if [[ -z $CODENAME ]]; then
	CODENAME="vts10"
fi
# New package name
if [[ -z $PKG_NAME ]]; then
	PKG_NAME="nginx-with-vts"
fi

# List of modules names - only for changelog purposes
if [[ -z $MODULES_NAME ]]; then
	MODULES_NAME="nginx-module-vts"
fi
# List of modules URL
if [[ -z $MODULES_URL ]]; then
	MODULES_URL="https://github.com/vozlt/nginx-module-vts/archive/v0.1.18.tar.gz"
	# MODULES_URL="https://github.com/vozlt/nginx-module-vts/archive/v0.1.18.tar.gz https://github.com/nginx-shib/nginx-http-shibboleth/archive/v2.0.1.tar.gz"
fi
